[{"link": "https://docs.python.org/3/tutorial/errors.html#errors-and-exceptions"}, {"link": "https://docs.python.org/3/library/exceptions.html#NameError"}, {"link": "https://docs.python.org/3/tutorial/errors.html#syntax-errors"}, {"link": "https://docs.python.org/3/tutorial/errors.html#exceptions"}, {"link": "https://docs.python.org/3/tutorial/errors.html#handling-exceptions"}, {"link": "https://docs.python.org/3/reference/simple_stmts.html#break"}, {"link": "https://docs.python.org/3/genindex.html"}, {"link": "https://docs.python.org/3/library/exceptions.html#bltin-exceptions"}, {"link": "https://docs.python.org/3/copyright.html"}, {"link": "https://docs.python.org/3/library/functions.html#print"}, {"link": "https://docs.python.org/3/tutorial/errors.html"}, {"link": "https://docs.python.org/3/bugs.html"}, {"link": "https://docs.python.org/3/reference/simple_stmts.html#raise"}, {"link": "https://docs.python.org/3/tutorial/errors.html#enriching-exceptions-with-notes"}, {"link": "https://docs.python.org/3/reference/compound_stmts.html#try"}, {"link": "https://docs.python.org/3/reference/datamodel.html#object.__str__"}, {"link": "https://docs.python.org/3/library/exceptions.html#BaseException"}, {"link": "https://docs.python.org/3/library/exceptions.html#Exception"}, {"link": "https://docs.python.org/3/reference/compound_stmts.html#finally"}, {"link": "https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt"}, {"link": "https://docs.python.org/3/reference/simple_stmts.html#continue"}, {"link": "https://docs.python.org/3/tutorial/errors.html#raising-and-handling-multiple-unrelated-exceptions"}, {"link": "https://docs.python.org/3/tutorial/inputoutput.html"}, {"link": "https://docs.python.org/3/library/exceptions.html#SystemExit"}, {"link": "https://docs.python.org/3/library/exceptions.html#ExceptionGroup"}, {"link": "https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions"}, {"link": "https://docs.python.org/bugs.html"}, {"link": "https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions"}, {"link": "https://docs.python.org/3/contents.html"}, {"link": "https://docs.python.org/3/reference/compound_stmts.html#with"}, {"link": "https://docs.python.org/3/library/exceptions.html#TypeError"}, {"link": "https://docs.python.org/3/tutorial/errors.html#raising-exceptions"}, {"link": "https://docs.python.org/3/tutorial/classes.html#tut-classes"}, {"link": "https://docs.python.org/3/index.html"}, {"link": "https://docs.python.org/3/tutorial/errors.html#exception-chaining"}, {"link": "https://docs.python.org/3/reference/compound_stmts.html#except"}, {"link": "https://docs.python.org/3/reference/simple_stmts.html#return"}, {"link": "https://docs.python.org/3/tutorial/classes.html"}, {"link": "https://docs.python.org/3/tutorial/index.html"}, {"link": "https://docs.python.org/license.html"}, {"link": "https://docs.python.org/3/library/exceptions.html#ZeroDivisionError"}, {"link": "https://docs.python.org/3/py-modindex.html"}, {"link": "https://docs.python.org/3/library/sys.html#sys.exit"}, {"link": "https://docs.python.org/3/tutorial/errors.html#predefined-clean-up-actions"}]